version: '3'

services:
  api:
    build: ./api
    container_name: api-beers
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    build: ./sql
    container_name: db-beers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
